# Generated by Django 5.0.3 on 2024-03-08 09:49

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pets.models
import types
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PetsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pets",
                    django_pydantic_field.fields.PydanticSchemaField(
                        blank=True,
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            typing.Union,
                            (
                                pets.models.Pets,
                                types.NoneType,
                            ),
                        ),
                    ),
                ),
            ],
        ),
    ]
