# Generated by Django 5.0.3 on 2024-03-08 09:37

import django.core.serializers.json
import django_pydantic_field.fields
import sample.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "json",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=sample.models.SampleArraySchema,
                    ),
                ),
            ],
        ),
    ]
