# Generated by Django 5.0.3 on 2024-03-08 09:39

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import sample.models
import types
import typing
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplemodel",
            name="json",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    typing.Union,
                    (
                        sample.models.SampleArraySchema,
                        types.NoneType,
                    ),
                ),
            ),
        ),
    ]
